// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sizqgefplggqmgbeovhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpenFnZWZwbGdncW1nYmVvdmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQxNzcsImV4cCI6MjA2MDYyMDE3N30.OjMKT1NTnkiqb2ajadiqBTsBGuF8qQec4F-SqZdmhC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);